services:
  # Inbound MX Server
  inbound_mx:
    build:
      context: ./mx
    container_name: inbound-mx
    restart: unless-stopped
    ports:
      - "25:25"
    networks:
      - mail_network
    depends_on:
      - mongodb
      - redis
    volumes:
      - certs:/etc/letsencrypt
      - ./mx/src/config:/config
    environment:
      - MONGO_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/ditmail?authSource=admin
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379

  # Outbound SMTP Server
  outbound_smtp:
    build:
      context: ./smtp
    container_name: outbound-smtp
    restart: unless-stopped
    ports:
      - "587:587"
      - "465:465"
    networks:
      - mail_network
    depends_on:
      - mongodb
      - redis
    volumes:
      - certs:/etc/letsencrypt
      - ./smtp/src/config:/config
    environment:
      - MONGO_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/ditmail?authSource=admin
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379
      
  acme_challenge:
    image: nginx:alpine
    container_name: acme-challenge
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - certbot_webroot:/var/www/certbot
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Add a simple nginx.conf

  # Certbot - For MX and SMTP
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - certs:/etc/letsencrypt
      - ./certbot-webroot:/var/www/certbot
      - ./smtp-fast/src/config:/config
    entrypoint: /bin/sh -c
    command: >
      "certbot certonly --non-interactive --force-renewal --webroot
      --webroot-path=/var/www/certbot
      --email admin@ditmail.online
      --agree-tos --no-eff-email
      --key-type ecdsa --elliptic-curve secp384r1
      -d mx.ditmail.online
      -d smtp.ditmail.online &&
      echo 'Copying certs to MX...' &&
      cp /etc/letsencrypt/live/mx.ditmail.online/privkey.pem /config/tls_key.pem &&
      cp /etc/letsencrypt/live/mx.ditmail.online/fullchain.pem /config/tls_cert.pem"

  # MongoDB
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    networks:
      - mail_network
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db

  # Redis
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - mail_network
    volumes:
      - redis_data:/data

networks:
  mail_network:
    driver: bridge

volumes:
  certs:
    driver: local
  mongo_data:
    driver: local
  redis_data:
    driver: local
