version: "3.8"

services:
  # Inbound MX Server (ditmail-mx)
  inbound_mx:
    build:
      context: ./mx
    container_name: inbound-mx
    restart: unless-stopped
    ports:
      - "25:25"
    networks:
      - mail_network
    depends_on:
      - mongodb
      - redis
      - certbot
    environment:
      - MONGO_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/ditmail?authSource=admin
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379
    volumes:
      - ./mx/src/config:/app/config
      - letsencrypt:/etc/letsencrypt

  # Outbound Submission Server (ditmail-smtp)
  outbound_smtp:
    build:
      context: ./smtp
    container_name: outbound-smtp
    restart: unless-stopped
    ports:
      - "587:587"
      - "465:465"
    networks:
      - mail_network
    depends_on:
      - mongodb
      - redis
      - certbot
    environment:
      - MONGO_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/ditmail?authSource=admin
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379
    volumes:
      - ./smtp/src/config:/app/config
      - letsencrypt:/etc/letsencrypt

  # WebSocket Server
  ws:
    build:
      context: ./ws
    container_name: ws
    restart: unless-stopped
    ports:
      - "4000:8080"
    networks:
      - mail_network
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379
      - JWT_SECRET=${JWT_SECRET}

  # Background Worker
  worker:
    build:
      context: ./worker
    container_name: worker
    restart: unless-stopped
    networks:
      - mail_network
    depends_on:
      - mongodb
      - redis
    environment:
      - MONGO_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/ditmail?authSource=admin
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379
      - JWT_SECRET=${JWT_SECRET}

  # MongoDB (Public with Auth)
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    networks:
      - mail_network
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db

  # Redis (Public with Password)
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - mail_network
    volumes:
      - redis_data:/data

  # Certbot for TLS (auto-renew)
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    restart: unless-stopped
    volumes:
      - letsencrypt:/etc/letsencrypt
      - certbot-logs:/var/log/letsencrypt
    entrypoint: >
      sh -c 'trap exit TERM;
      while :; do
        certbot certonly --standalone --agree-tos --no-eff-email
        -m admin@ditmail.online
        -d mx.ditmail.online
        -d smtp.ditmail.online;
        certbot renew --quiet;
        sleep 12h & wait $${!};
      done'

networks:
  mail_network:
    driver: bridge

volumes:
  mongo_data:
    driver: local
  redis_data:
    driver: local
  letsencrypt:
    driver: local
  certbot-logs:
    driver: local
